---
title: "Consume and Reduce Paper Review Spreadsheet"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "googledrive",
                     "readxl")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector){
  library(package, character.only = TRUE)
}

```

# Remote I-O
```{r remote-io}
external_dir <- "../data/external/"
interim_dir <- "../data/interim/"
google_drive_path <- "~/project_chandra_bot/"
google_drive_file_name <- "paper_review_details_2019.xlsx"

output_for_tableau_file_name <- paste0(interim_dir, "paper_review_for_tableau.csv")

local_xlxs_file_name <- paste0(external_dir, "editorial_manager/", google_drive_file_name)

session_groups_file_name <- paste0(interim_dir, "session_groups_number_2.csv")

```

# Parameters
```{r parameters}
MAX_SCORE <- 5L
ACCEPT_WORD <- "Accept"
REJECT_WORD <- "Reject"
ACCEPT_DEFAULT_SCORE <- 4L
REJECT_DEFAULT_SCORE <- 2L
```


# Data Reads
```{r data-read}
drive_download(file = paste0(google_drive_path, google_drive_file_name),
               path = local_xlxs_file_name,
               overwrite = TRUE)

raw_df <- read_excel(path = local_xlxs_file_name, col_names = LETTERS[1:10])

session_groups_df <- read_csv(session_groups_file_name, col_types = "cic")

```

# Data Reduction
```{r data-reduction}
paper_numbers_df <- raw_df %>%
  filter(str_detect(A, "20-")) %>%
  select(paper_number = A)

check_dups_df <- paper_numbers_df %>%
  group_by(paper_number) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  filter(count > 1)

working_df <- raw_df %>%
  filter(str_detect(B, "Presentation")) %>%
  rename(article_title = A,
         article_type = B,
         required_reviewers = C,
         reviewer_number = D,
         confidential_comments = E,
         reviewer_comments_to_author = F,
         reviewer_recommendation = G,
         review_complete = H,
         editorial_status = I,
         overall_score_for_presentation = J)
  
article_title_df <- tibble(article_title = unique(working_df$article_title)) %>%
  bind_cols(., paper_numbers_df)

review_details_df <- left_join(article_title_df, working_df, by = c("article_title")) %>%
  type_convert(., col_types = cols(.default = col_character(),
                                   required_reviewers = col_integer(),
                                   reviewer_number = col_integer(),
                                   review_complete = col_logical(),
                                   overall_score_for_presentation = col_integer())) %>%
  mutate(confidential_comments = gsub("\r?\n|\r", " ", confidential_comments)) %>%
  mutate(reviewer_comments_to_author = gsub("\r?\n|\r", " ", reviewer_comments_to_author)) %>%
  mutate(overall_score_for_presentation = if_else(overall_score_for_presentation > MAX_SCORE,
                                                  if_else(reviewer_recommendation == ACCEPT_WORD, 
                                                          ACCEPT_DEFAULT_SCORE, 
                                                          REJECT_DEFAULT_SCORE),
                                                  overall_score_for_presentation)) %>%
  mutate(accepts = if_else(reviewer_recommendation == ACCEPT_WORD, 1L, 0L)) %>%
  mutate(accepts = if_else(is.na(accepts), 0L, accepts)) %>%
  mutate(valid_reviews = if_else(reviewer_recommendation %in% c(ACCEPT_WORD, REJECT_WORD), 1L, 0L)) %>%
  group_by(paper_number, article_title) %>%
  mutate(acceptance_rate = sum(accepts) / sum(valid_reviews)) %>%
  ungroup() %>%
  select(-accepts, -valid_reviews) %>%
  left_join(., session_groups_df, by = c("paper_number"))

check_high_scores_df <- review_details_df %>%
  filter(overall_score_for_presentation > MAX_SCORE)

remove(working_df, article_title_df)
  

```

# Data Write
```{r data-write}
write.csv(review_details_df, file = output_for_tableau_file_name, quote = TRUE, row.names = FALSE)
```

