---
title: "Make 2020 Data"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "googledrive",
                     "readxl")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I-O
```{r remote-io}
source("hash-method.R")

external_dir <- "../../data/external/"
interim_dir <- "../../data/interim/"
processed_dir <- "../../data/processed/"

canonical_human_file_name <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vTGm3PUsUUSFAuXHPGl_gFwHAqnAOaSWCTwrSI6IgKNHWSHWZvt3cS67GNB40mqHYsuoH_FOA3SPRhO/pub?gid=0&single=true&output=csv"

local_canonical_human_file_name <- paste0(interim_dir, "canonical_humans.csv")

private_google_drive_path <- "~/project_chandra_bot/"
private_editorial_board_database <- "ADB40 2020 papers.xlsx"
private_committee_decisions_file_name <- "adb40-annual-meeting-2020-decisions"

local_editorial_board_database_file_name <- 
  paste0(external_dir, "editorial_manager/", private_editorial_board_database)
local_committee_decisions_file_name <- paste0(external_dir, "adb40-annual-meeting-2020-decisions.csv")

output_humans_file_name <- paste0(processed_dir, "confidential-humans-2020.csv")
output_reviews_file_name <- paste0(processed_dir, "confidential-reviews-2020.csv")
output_papers_file_name <- paste0(processed_dir, "confidential-papers-2020.csv")
```

# Parameters
```{r parameters}
MAX_SCORE <- 5L
YEAR <- 2020

pub_decision_dict_df <- tibble(bot_names = c("ACCEPT",
                                             "REJECT",
                                             NA,
                                             "ACCEPT_CORRECT",
                                             "ACCEPT"),
                               editorial_names = c("Completed Accept",
                                                   "Completed Reject",
                                                   "Required Reviews Completed",
                                                   "Revise",
                                                   "With Editor"))
```


# Data Reads
```{r data-reads}
canonical_human_df <- read_csv(canonical_human_file_name, 
                               col_types = cols(.default = col_character()))

drive_download(file = paste0(private_google_drive_path, private_editorial_board_database),
               path = local_editorial_board_database_file_name,
               overwrite = TRUE)

input_reviews_df <- read_excel(path = local_editorial_board_database_file_name, 
                               col_names = LETTERS[1:12])

drive_download(file = paste0(private_google_drive_path, private_committee_decisions_file_name),
               path = local_committee_decisions_file_name,
               overwrite = TRUE)

committee_decisions_df <- read_csv(local_committee_decisions_file_name, col_types = "ccc")

```

# Build Reviews Database
```{r build-review}
working_df <- slice(input_reviews_df, 5:n())
colnames(working_df) <- slice(input_reviews_df, 4:4)
reviews_df <- working_df %>%
  select(paper_id = 'Manuscript Number',
         title = 'Article Title',
         reviewer_name = 'Reviewer Name',
         commentary_to_chair = 'Reviewer Comments to Editor',
         commentary_to_author = 'Reviewer Comments to Author',
         presentation_recommend = 'Reviewer Recommendation',
         editorial_status = 'Editorial Status',
         presentation_score = 'Overall score for Presentation') %>%
  mutate(presentation_score = as.numeric(presentation_score)) %>%
  mutate(presentation_score = if_else(presentation_score > MAX_SCORE, 
                                      presentation_score / 2.0, 
                                      presentation_score)) %>%
  mutate(year = YEAR) %>%
  mutate(reviewer_name = gsub("[a-zA-z]{3}[0-9]{2}", "", reviewer_name, ignore.case = TRUE)) %>%
  mutate(reviewer_name = gsub("[a-zA-z]{2}[0-9]{3}", "", reviewer_name, ignore.case = TRUE)) %>%
  mutate(reviewer_name = gsub("[\\(][0-9][\\)]", "", reviewer_name)) %>%
  mutate(reviewer_name = trimws(reviewer_name))

remove(working_df)
```

# Reconcile Humans with Canonical
```{r reconcile}
key_human_df <- select(canonical_human_df, canonical_name, affiliation) %>%
  mutate(join_name = canonical_name)

alias_01_human_df <- select(canonical_human_df, canonical_name, affiliation, alias_01) %>%
  filter(!is.na(alias_01)) %>%
  rename(join_name = alias_01)

alias_02_human_df <- select(canonical_human_df, canonical_name, affiliation, alias_02) %>%
  filter(!is.na(alias_02)) %>%
  rename(join_name = alias_02)

join_human_df <- bind_rows(key_human_df, alias_01_human_df, alias_02_human_df)

review_human_df <- distinct(reviews_df, reviewer_name)

working_df <- left_join(review_human_df, join_human_df, by = c("reviewer_name" = "join_name")) %>%
  rowwise() %>%
  mutate(hash = hash_function(canonical_name, affiliation)) %>%
  ungroup()

output_review_df <- left_join(reviews_df, working_df, by = c("reviewer_name")) %>%
  select(year, paper_id, title, reviewer_hash = hash,
         commentary_to_chair, commentary_to_author,
         presentation_recommend, presentation_score, 
         editorial_status) %>%
  left_join(., pub_decision_dict_df, by = c("editorial_status" = "editorial_names")) %>%
  rename(committee_publication_decision = bot_names) %>%
  select(-editorial_status) %>%
  left_join(., select(committee_decisions_df, paper_id, 
                      prez_dec = committee_decision),
            by = c("paper_id")) %>%
  mutate(prez_dec = toupper(prez_dec)) %>%
  mutate(prez_dec = if_else(prez_dec == "PODIUM", "ACCEPT", prez_dec)) %>%
  rename(committee_presentation_decision = prez_dec) %>%
  mutate(commentary_to_chair = str_replace_all(commentary_to_chair, '\\"', "'")) %>%
  mutate(commentary_to_author = str_replace_all(commentary_to_author, '\\"', "'")) %>%
  mutate(commentary_to_chair = gsub("\r?\n|\r", " ", commentary_to_chair)) %>%
  mutate(commentary_to_author = gsub("\r?\n|\r", " ", commentary_to_author)) 

join_aliases_df <- canonical_human_df %>%
  mutate(aliases = paste(alias_01, alias_02, sep = ",")) %>%
  mutate(previous_affiliation = paste(previous_affiliation_01,
                                      previous_affiliation_02,
                                      previous_affiliation_03,
                                      previous_affiliation_04,
                                      previous_affiliation_05,
                                      sep = ",")) %>%
  select(canonical_name, aliases, affiliation, previous_affiliation)
           
output_human_df <- left_join(select(working_df, canonical_name, affiliation, hash),
                             join_aliases_df, by = c("canonical_name", "affiliation")) %>%
  select(name = canonical_name,
         current_affiliation = affiliation,
         aliases,
         previous_affiliation,
         hash_id = hash)

output_paper_df <- committee_decisions_df %>%
  select(paper_id, prez_dec = committee_decision) %>%
  left_join(select(reviews_df, paper_id, year, title, pub_dec = editorial_status),
            .,
            by = c("paper_id")) %>%
  mutate(prez_dec = toupper(prez_dec)) %>%
  mutate(prez_dec = if_else(prez_dec == "PODIUM", "ACCEPT", prez_dec)) %>%
  left_join(., pub_decision_dict_df, by = c("pub_dec" = "editorial_names")) %>%
  select(paper_id,
         year,
         title,
         committee_presentation_decision = prez_dec,
         committee_publication_decision = bot_names)
```


```{r write-data}
write_csv(output_human_df, path = output_humans_file_name)
write_csv(output_review_df, path = output_reviews_file_name)
write_csv(output_paper_df, path = output_papers_file_name)

drive_find(output_humans_file_name) %>% drive_rm()
drive_find(output_reviews_file_name) %>% drive_rm()
drive_find(output_papers_file_name) %>% drive_rm()

drive_upload(output_humans_file_name,
             path = private_google_drive_path)

drive_upload(output_reviews_file_name,
             path = private_google_drive_path)

drive_upload(output_papers_file_name,
             path = private_google_drive_path)
```

