---
title: "Make Names Database"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector){
  library(package, character.only = TRUE)
}

```

# Remote I-O
```{r remote-io}
external_dir <- "../../data/external/"
interim_dir <- "../../data/interim/"

first_name_file_name <- "https://raw.githubusercontent.com/smashew/NameDatabases/master/NamesDatabases/first%20names/us.txt"

last_name_file_name <- "https://raw.githubusercontent.com/smashew/NameDatabases/master/NamesDatabases/surnames/us.txt"

output_first_file_name <- paste0(interim_dir, "first-names.RDS")
output_last_file_name <- paste0(interim_dir, "last-names.RDS")

```

# Data Reads
```{r data-reads}
raw_first_names_df <- read_csv(first_name_file_name, col_names = FALSE, col_types = "c")
raw_last_names_df <- read_csv(last_name_file_name, col_names = FALSE, col_types = "c")
```

# Clean Data
```{r clean-data}
first_names_df <- raw_first_names_df %>%
  rename(first = X1)

last_names_df <- raw_last_names_df %>%
  rename(last = X1)

```

# Write Data
```{r write-data}
saveRDS(first_names_df, file = output_first_file_name)
saveRDS(last_names_df, file = output_last_file_name)
```


