---
title: "Make Data"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("httpuv",
                     "rorcid",
                     "googledrive",
                     "readxl",
                     "tidyverse")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I-O
```{r remote-io}
source("hash-method.R")

external_dir <- "../../data/external/"
interim_dir <- "../../data/interim/"
confidential_dir <- "~/Documents/Confidential/"
secrets_dir <- "~/Documents/"

canonical_human_file_name <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vTGm3PUsUUSFAuXHPGl_gFwHAqnAOaSWCTwrSI6IgKNHWSHWZvt3cS67GNB40mqHYsuoH_FOA3SPRhO/pub?gid=0&single=true&output=csv"

local_canonical_human_file_name <- paste0(interim_dir, "canonical_humans.csv")

private_google_drive_path <- "~/project_chandra_bot/"

papers_2019_file_name <- "ADB40 2019 Papers.xlsx"
papers_2020_file_name <- "ADB40 2020 Papers.xlsx"
papers_2021_file_name <- "AEP50 2021 Papers.xlsx"

decisions_2019_file_name <- "adb40-annual-meeting-2019-decisions" 
decisions_2020_file_name <- "adb40-annual-meeting-2020-decisions"
decisions_2021_file_name <- "aep50-annual-meeting-2021-decisions"

verified_file_name <- "aep50-verified-reviewers"

fetch_df <- tibble(private = c(papers_2019_file_name,
                               papers_2020_file_name,
                               papers_2021_file_name,
                               decisions_2019_file_name,
                               decisions_2020_file_name,
                               decisions_2021_file_name,
                               verified_file_name),
                   local = c(paste0(confidential_dir, papers_2019_file_name),
                             paste0(confidential_dir, papers_2020_file_name),
                             paste0(confidential_dir, papers_2021_file_name),
                             paste0(confidential_dir, decisions_2019_file_name, ".csv"),
                             paste0(confidential_dir, decisions_2020_file_name, ".csv"),
                             paste0(confidential_dir, decisions_2021_file_name, ".csv"),
                             paste0(confidential_dir, verified_file_name, ".csv")))

output_humans_file_name <- paste0(confidential_dir, "confidential-humans.csv")
output_reviews_file_name <- paste0(confidential_dir, "confidential-reviews.csv")
output_papers_file_name <- paste0(confidential_dir, "confidential-papers.csv")
```

# Parameters
```{r parameters}
max_score_df <- tibble(year = c(2019, 2020, 2021),
                       max_score = c(5, 5, 10))

pub_decision_dict_df <- tibble(bot_names = c("ACCEPT",
                                             "REJECT",
                                             NA,
                                             "ACCEPT_CORRECT",
                                             "ACCEPT"),
                               editorial_names = c("Completed Accept",
                                                   "Completed Reject",
                                                   "Required Reviews Completed",
                                                   "Revise",
                                                   "With Editor"))

dict_2019_df <- tibble(review_recommendation = c("Accept: Presentation and Publication",
                                                 "Accept: Presentation Only",
                                                 "Accept: Presentation; Reject: Publication",
                                                 "Accept: Presentation; Revise: Publication",
                                                 "Accept: Publication Only",
                                                 "Reject: Presentation and Publication",
                                                 "Reject: Presentation Only",
                                                 "Reject: Publication Only"),
                       presentation_recommendation = c("Accept",
                                                       "Accept",
                                                       "Accept",
                                                       "Accept",
                                                       "None",
                                                       "Reject",
                                                       "Reject",
                                                       "None"),
                       publication_recommendation = c("Accept",
                                                      "None",
                                                      "Reject",
                                                      "Accept_Correct",
                                                      "Accept",
                                                      "Reject",
                                                      "None",
                                                      "Reject"))

dict_df <- tibble(review_recommendation = c("Accept",
                                            "Reject"),
                  presentation_recommendation = c("Accept",
                                                  "Reject"),
                  publication_recommendation = c("Accept",
                                                 "Reject"))

recommendation_dict_df <- bind_rows(
  mutate(dict_2019_df, year = 2019L),
  mutate(dict_df, year = 2020L),
  mutate(dict_df, year = 2021L)
)

remove(dict_df, dict_2019_df)

```

# Data Reads
```{r data-reads}
canonical_human_df <- read_csv(canonical_human_file_name, 
                               col_types = cols(.default = col_character()))

for (row in nrow(fetch_df)) {
  
  private_file_name <- slice(fetch_df, row:row)$private
  local_file_name <- slice(fetch_df, row:row)$local
  
  drive_download(file = private_file_name,
               path = local_file_name,
               overwrite = TRUE)
}

input_2019_reviews_df <- read_excel(path = paste0(confidential_dir, papers_2019_file_name), 
                               col_names = LETTERS[1:12])

input_2020_reviews_df <- read_excel(path = paste0(confidential_dir, papers_2020_file_name), 
                               col_names = LETTERS[1:12])

input_2021_reviews_df <- read_excel(path = paste0(confidential_dir, papers_2021_file_name), 
                               col_names = LETTERS[1:20])

committee_decisions_df <- bind_rows(
  read_csv(paste0(confidential_dir, decisions_2019_file_name, ".csv"), col_types = "ccc"),
  read_csv(paste0(confidential_dir, decisions_2020_file_name, ".csv"), col_types = "ccc"),
  read_csv(paste0(confidential_dir, decisions_2021_file_name, ".csv"), col_types = "ccc"))

verified_reviewers_vector <- read_csv(
  paste0(confidential_dir, verified_file_name, ".csv"), col_types = "c"
  )$canonical_name

```

# Build Reviews Database
```{r build-review}
working_2021_df <- slice(input_2021_reviews_df, 5:n())
colnames(working_2021_df) <- slice(input_2021_reviews_df, 4:4)
working_2021_df <- mutate(working_2021_df, year = 2021) %>%
  rename(
    `Overall score for Presentation` = 
      `How strongly would you recommend this for presentation at the annual meeting?`)

working_2020_df <- slice(input_2020_reviews_df, 5:n())
colnames(working_2020_df) <- slice(input_2020_reviews_df, 4:4)
working_2020_df <- mutate(working_2020_df, year = 2020)

working_2019_df <- slice(input_2019_reviews_df, 5:n())
colnames(working_2019_df) <- slice(input_2019_reviews_df, 4:4)
working_2019_df <- mutate(working_2019_df, year = 2019)

reviews_df <- bind_rows(working_2021_df, working_2020_df, working_2019_df) %>%
  select(paper_id = 'Manuscript Number',
         title = 'Article Title',
         type = 'Article Type',
         reviewer_name = 'Reviewer Name',
         commentary_to_chair = 'Reviewer Comments to Editor',
         commentary_to_author = 'Reviewer Comments to Author',
         review_recommendation = 'Reviewer Recommendation',
         editorial_status = 'Editorial Status',
         presentation_score = 'Overall score for Presentation',
         year) %>%
  left_join(., max_score_df, by = c("year")) %>%
  mutate(presentation_score = as.numeric(presentation_score)) %>%
  mutate(presentation_score = if_else(presentation_score > max_score, 
                                      presentation_score / 2.0 / max_score, 
                                      presentation_score / max_score)) %>%
  mutate(reviewer_name = gsub("[a-zA-z]{3}[0-9]{2}", "", reviewer_name, ignore.case = TRUE)) %>%
  mutate(reviewer_name = gsub("[a-zA-z]{2}[0-9]{3}", "", reviewer_name, ignore.case = TRUE)) %>%
  mutate(reviewer_name = gsub("[\\(][0-9][\\)]", "", reviewer_name)) %>%
  mutate(reviewer_name = trimws(reviewer_name))

remove(working_2019_df, working_2020_df, working_2021_df)
```

# Reconcile Humans with Canonical
```{r reconcile}
key_human_df <- select(canonical_human_df, canonical_name, affiliation, 
                       orcid_url, last_degree_affiliation) %>%
  mutate(join_name = canonical_name)

alias_01_human_df <- select(canonical_human_df, canonical_name, affiliation, 
                            orcid_url, last_degree_affiliation, alias_01) %>%
  filter(!is.na(alias_01)) %>%
  rename(join_name = alias_01)

alias_02_human_df <- select(canonical_human_df, canonical_name, affiliation, 
                            orcid_url, last_degree_affiliation, alias_02) %>%
  filter(!is.na(alias_02)) %>%
  rename(join_name = alias_02)

join_human_df <- bind_rows(key_human_df, alias_01_human_df, alias_02_human_df)

review_human_df <- distinct(reviews_df, reviewer_name)

working_df <- left_join(review_human_df, join_human_df, by = c("reviewer_name" = "join_name")) %>%
  rowwise() %>%
  mutate(hash = hash_function(canonical_name, orcid_url, last_degree_affiliation)) %>%
  ungroup()

missing_humans_df <- filter(working_df, is.na(canonical_name))

matched_humans_df <- working_df

remove(key_human_df, alias_01_human_df, alias_02_human_df, join_human_df, review_human_df,
       working_df)
```

# Prepare Outputs
```{r prepare-outputs}
output_review_df <- left_join(reviews_df, matched_humans_df, by = c("reviewer_name")) %>%
  select(year, paper_id, type, title, reviewer_human_hash_id = hash,
         commentary_to_chair, commentary_to_author,
         review_recommendation, presentation_score, 
         editorial_status) %>%
  left_join(., recommendation_dict_df, by = c("review_recommendation", "year")) %>%
  select(-review_recommendation) %>%
  mutate(publication_recommendation = if_else(year %in% c(2020L,2021L) & type == "Presentation",
                                              "None",
                                              publication_recommendation)) %>%
  mutate(presentation_recommendation = replace_na(presentation_recommendation, "None")) %>%
  mutate(publication_recommendation = replace_na(publication_recommendation, "None")) %>%
  left_join(., pub_decision_dict_df, by = c("editorial_status" = "editorial_names")) %>%
  rename(committee_publication_decision = bot_names) %>%
  mutate(committee_publication_decision = replace_na(committee_publication_decision, "None")) %>%
  select(-editorial_status) %>%
  left_join(., select(committee_decisions_df, paper_id, 
                      prez_dec = committee_decision),
            by = c("paper_id")) %>%
  mutate(prez_dec = toupper(prez_dec)) %>%
  mutate(prez_dec = if_else(prez_dec == "PODIUM", "ACCEPT", prez_dec)) %>%
  mutate(prez_dec = replace_na(prez_dec, "None")) %>%
  rename(committee_presentation_decision = prez_dec) %>%
  mutate(commentary_to_chair = str_replace_all(commentary_to_chair, '\\"', "'")) %>%
  mutate(commentary_to_chair = gsub("\r?\n|\r", " ", commentary_to_chair)) %>%
  mutate(commentary_to_chair = replace_na(commentary_to_chair, "None")) %>%
  mutate(commentary_to_author = str_replace_all(commentary_to_author, '\\"', "'")) %>%
  mutate(commentary_to_author = gsub("\r?\n|\r", " ", commentary_to_author)) %>%
  mutate(commentary_to_author = replace_na(commentary_to_author, "None")) 

join_aliases_df <- canonical_human_df %>%
  mutate(aliases = paste(alias_01, alias_02, sep = ",")) %>%
  mutate(previous_affiliation = paste(previous_affiliation_01,
                                      previous_affiliation_02,
                                      previous_affiliation_03,
                                      previous_affiliation_04,
                                      previous_affiliation_05,
                                      sep = ",")) %>%
  select(canonical_name, aliases, affiliation, previous_affiliation)
           
output_human_df <- left_join(
  select(matched_humans_df, canonical_name, affiliation, orcid_url, last_degree_affiliation, hash),
  join_aliases_df, by = c("canonical_name", "affiliation")) %>%
  mutate(orcid = str_replace(orcid_url, "https://orcid.org/", "")) %>%
  mutate(verified = canonical_name %in% verified_reviewers_vector) %>%
  select(name = canonical_name,
         current_affiliation = affiliation,
         aliases,
         previous_affiliation,
         orcid,
         orcid_url,
         last_degree_affiliation,
         hash_id = hash,
         verified)

join_df <- distinct(reviews_df, paper_id, year, title, pub_dec = editorial_status) %>%
  group_by(paper_id, year, title) %>%
  summarise(pub_dec = min(pub_dec), .groups = "drop") %>%
  ungroup()

output_paper_df <- committee_decisions_df %>%
  group_by(paper_id) %>%
  summarise(prez_dec = min(committee_decision), .groups = "drop") %>%
  ungroup() %>%
  left_join(join_df, ., by = c("paper_id")) %>%
  mutate(prez_dec = toupper(prez_dec)) %>%
  mutate(prez_dec = if_else(prez_dec == "PODIUM", "ACCEPT", prez_dec)) %>%
  left_join(., pub_decision_dict_df, by = c("pub_dec" = "editorial_names")) %>%
  mutate(prez_dec = replace_na(prez_dec, "None")) %>%
  mutate(bot_names = replace_na(bot_names, "None")) %>%
  select(paper_id,
         year,
         title,
         committee_presentation_decision = prez_dec,
         committee_publication_decision = bot_names)
```

# Write to Disk
```{r write-data}
write_csv(output_human_df, path = output_humans_file_name)
write_csv(output_review_df, path = output_reviews_file_name)
write_csv(output_paper_df, path = output_papers_file_name)

```

# Push Back to Google Drive
```{r push-drive}

drive_find(output_humans_file_name) %>% drive_rm()
drive_find(output_reviews_file_name) %>% drive_rm()
drive_find(output_papers_file_name) %>% drive_rm()

drive_upload(output_humans_file_name,
             path = private_google_drive_path)

drive_upload(output_reviews_file_name,
             path = private_google_drive_path)

drive_upload(output_papers_file_name,
             path = private_google_drive_path)
```
