---
title: "Make Article Titles Database"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I-O
```{r remote-io}
external_dir <- "../../data/external/"
interim_dir <- "../../data/interim/"

# https://www.jstor.org/open/
article_titles_file_name <- paste0(external_dir, "random_article_titles.txt")

output_file_name <- paste0(interim_dir, "article-titles.RDS")

```

# Data Reads
```{r data-reads}
# titles data not in quotes
input_line <- readLines(article_titles_file_name)
raw_article_titles_df <- tibble(title = input_line)
```

# Clean Data
```{r clean-data}
article_titles_df <- raw_article_titles_df %>%
  mutate(length = str_length(title)) %>%
  filter(length > 4) %>%
  select(article_title = title, -length) 
```

# Write Data
```{r write-data}
saveRDS(article_titles_df, file = output_file_name)
```


