---
html_document:
  theme: cosmo
  toc: yes
output:
  html_document:
    df_print: paged
title: "Common Corridor Languages"
---

## Administration

#### Purpose
Extract Abstracts from TRB Paper submissions

## Action

#### Overhead
```{r overhead, include = FALSE}
# install and load libraries
packages_vector <- c("tm",
                     "tidyverse",
                     "googledrive",
                     "fuzzyjoin",
                     "hunspell",
                     "pdftools",
                     "pdfsearch",
                     "textreadr",
                     "readtext",
                     "qdapRegex",
                     "stringr",
                     "staplr",
                     "textclean")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector){
  library(package, character.only = TRUE)
}

```

#### Remote I/O
```{r remote-io}
google_drive_path <- "~/project_chandra_bhat/papers/2020/"

papersfromdrive <- drive_find(q = "name contains '20-0'", type = "pdf")

submittedpapersfromdrive <- papersfromdrive[-grep("_reviewer", papersfromdrive$name),]

input_dir <- "C:/Projects/ChandraBot/Papers/"
output_dir <- "C:/Projects/ChandraBot/Output/"
author_submission_data <- paste0(output_dir, "submitted-papers-author-data.RDS")
output_file_name <- paste0(output_dir, "submitted_paper-author_data.csv")

```

#### Data Reads 
```{r data-reads}

submitted_paper_pdfs <- paste(input_dir, list.files(input_dir, pattern = "*.pdf"), sep = "")
submitted_paper_pdf_names <- list.files(input_dir, pattern = "*.pdf")
submitted_paper_pdf_text <- map(submitted_paper_pdfs, ~ pdf_text(.x)[1:2]) %>%
  gsub("[\r\n]", "", .)
submitted_paper_raw_df <- data_frame(document = submitted_paper_pdf_names, text = submitted_paper_pdf_text) %>%
  mutate(text = gsub("[\r\n\r\t\v]", "", text))

rm(submitted_paper_pdfs, submitted_paper_pdf_names, submitted_paper_pdf_text)

```

## Data Reduction
```{r data-reduction}

filename <- submitted_paper_raw_df %>%
  pull(document) 

text <- submitted_paper_raw_df %>%
  pull(text) 
  
author_submission_df <- data_frame(filename, text) %>%
  mutate(Full_Title = qdapRegex::ex_between(as.character(text), "Full Title:", "Abstract:"),
         Abstract = qdapRegex::ex_between(as.character(text), "Abstract:", "Manuscript Classifications:"),
         Manuscript_Class = qdapRegex::ex_between(as.character(text), "Manuscript Classifications:", "Manuscript Number:"),
         Manuscript_Number = qdapRegex::ex_between(as.character(text), "Manuscript Number:", "Article Type:"),
         Article_Type = replace_white(qdapRegex::ex_between(as.character(text), "Article Type:", "Order of Authors:")),
         Authors = qdapRegex::ex_between(as.character(text), "Order of Authors:", "Powered by Editorial"),
         Email = regmatches(as.character(text), gregexpr("([_a-z0-9-]+(\\.[_a-z0-9-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,4}))", as.character(text)))) %>%
  mutate(Full_Title = gsub("[\r\n]", " ", str_wrap(Full_Title, width = 0.9, indent = 0.9)), 
         Abstract = gsub("[\r\n]", " ", str_wrap(Abstract, width = 0.9, indent = 0.9)),
         Manuscript_Class = gsub("[\r\n]", " ", str_wrap(Manuscript_Class,width = 0.9, indent = 0.9)),
         Manuscript_Number = gsub("[\\r\\n\\r\\t\\v]", "", Manuscript_Number),
         Article_Type = gsub("[\r\n]", "", Article_Type),
         Authors = gsub("[\r\n]", " ", str_wrap(Authors,width = 0.9, indent = 0.9))) %>%
  select(filename = filename, Full_Title, Abstract, Manuscript_Class, Manuscript_Number, Article_Type, Authors, Email) 

Email <- as.data.frame(matrix(author_submission_df$Email), nrow=length(unlist(author_submission_df$Email[1]))) %>%
  mutate(filename = author_submission_df$filename) 
  
  e <- matrix(author_submission_df$Email)
email_df <- data.frame(V1 = rep(Email$filename, sapply(e, length)), V2 = unlist(e)) %>%
  select(filename = V1, Email = V2)


author_submission_df <- author_submission_df %>%
  left_join(email_df, by = "filename") %>%
  select(filename, Full_Title, Abstract, Manuscript_Class, Manuscript_Number, Article_Type, Authors, Email = Email.y)

  
rm(filename,text, Email, e)
```



### Data Write
```{r data-write}

saveRDS(author_submission_df, file = author_submission_data)

write_csv(author_submission_df, path = output_file_name)

drive_upload(output_file_name,"submitted_paper-author_data.csv", type= "spreadsheet")

```
