---
title: "Make Affiliations Database"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I-O
```{r remote-io}
external_dir <- "../../data/external/"
interim_dir <- "../../data/interim/"

# https://ope.ed.gov/dapip/#/download-data-files
university_file_name <- paste0(external_dir, "InstitutionCampus.csv")

output_file_name <- paste0(interim_dir, "affiliations.RDS")

```

# Data Reads
```{r data-reads}
raw_university_df <- read_csv(university_file_name, col_types = cols(.default = col_character()))
```

# Clean Data
```{r clean-data}
remove_word_vector <- c("Community", "Vocational", "Inc", "Ltd", "Beauty", "Cosmetology",
                        "Hair", "Visual", "Technical", "Training", "Technical",
                        "Junior", "Barber", "Montessori", "Bible", "Animal", "Tractor",
                        "Art", "Design", "Career", "Professional", "Learning", 
                        "Nail", "Salon", "Culinary", "Film", "Language",
                        "English", "Medical", "Paul Mitchell", "Nursing", "Theological",
                        "Business", "Trade", "Applied", "Divinity")

university_df <- raw_university_df %>%
  filter(LocationType == "Institution") %>%
  select(affiliation = LocationName) %>%
  distinct(affiliation)

for (remove_word in remove_word_vector) {
  
  university_df <- university_df %>%
    filter(!str_detect(affiliation, remove_word))
  
}
```

# Write Data
```{r write-data}
saveRDS(university_df, file = output_file_name)
```


